#!/usr/bin/env python3
"""
Test email functionality for pixel monitoring system
"""

import os
import sys
import smtplib
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart
from datetime import datetime

# Import configuration from the main system
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from pixel_notification_monitor import NOTIFICATION_CONFIG, logger

def test_email_configuration():
    """Test the email configuration and send a test message"""

    print("🧪 Testing Email Configuration...")
    print("=" * 50)

    # Check configuration
    email_config = NOTIFICATION_CONFIG['email']
    print(f"✅ Email Enabled: {email_config['enabled']}")
    print(f"✅ SMTP Server: {email_config['smtp_server']}:{email_config['smtp_port']}")
    print(f"✅ From Email: {email_config['from_email']}")
    print(f"✅ To Email: {email_config['to_emails']}")

    # Check password
    password = os.getenv('EMAIL_PASSWORD', email_config.get('password', ''))
    if not password:
        print("❌ No email password configured!")
        print("Set EMAIL_PASSWORD environment variable first.")
        return False

    print(f"✅ Password: {'*' * len(password)} (configured)")

    # Create test message
    subject = f"🧪 Pixel Monitor Test Email - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

    test_message = f"""🔥 Pixel Monitoring System - Test Email 🔥

This is a test email from your Enhanced Pixel Monitoring System!

✅ Email alerts are now configured and working
✅ Recipient: {email_config['to_emails'][0]}
✅ System: Enhanced ML-Powered Detection
✅ Test Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

🎯 What This Means:
When pixel issues are detected in Jira, you'll receive instant email alerts with:
- Ticket details and direct links
- ML confidence scores
- Detection reasoning
- Dashboard integration links

🚨 Next Alert:
The system will automatically email you when the next pixel-related ticket is found!

Generated by Enhanced Pixel Monitoring System
Samsung Ads Performance Team
"""

    try:
        print("\n📧 Sending test email...")

        # Create message
        msg = MimeMultipart()
        msg['From'] = email_config['from_email']
        msg['To'] = ', '.join(email_config['to_emails'])
        msg['Subject'] = subject
        msg.attach(MimeText(test_message, 'plain'))

        # Send via SMTP
        server = smtplib.SMTP(email_config['smtp_server'], email_config['smtp_port'])
        server.starttls()
        server.login(email_config['from_email'], password)

        text = msg.as_string()
        server.sendmail(
            email_config['from_email'],
            email_config['to_emails'],
            text
        )
        server.quit()

        print(f"✅ SUCCESS! Test email sent to {email_config['to_emails'][0]}")
        print(f"📧 Subject: {subject}")
        print("\n🎉 Email alerts are now fully operational!")
        print("\n📋 Next Steps:")
        print("1. Check your inbox for the test email")
        print("2. Your enhanced pixel monitor will now send email alerts")
        print("3. When pixel issues are detected, you'll get instant notifications")

        return True

    except Exception as e:
        print(f"❌ FAILED to send test email: {e}")
        print("\n🔧 Troubleshooting:")
        print("- Check if your Samsung email password is correct")
        print("- If you have 2FA enabled, use an App Password instead")
        print("- Verify SMTP settings for your email provider")

        return False

if __name__ == "__main__":
    success = test_email_configuration()

    if success:
        print(f"\n🚀 Email alerts are ready! Your Enhanced Pixel Monitor will now send")
        print(f"   instant notifications to {NOTIFICATION_CONFIG['email']['to_emails'][0]}")
        print(f"   whenever pixel issues are detected in Jira.")
    else:
        print(f"\n⚠️ Email setup needs attention. Please check the configuration.")